#+title: Spørsmål om dataene

Noen spørsmål angående datasettet for Rusundersøkelsen 2024.

* Verdi som ikke finnes i kodebok
Er disse feilkodet? De skal uansett omkodet til missing.
- Variable =Drukket1= har verdi 8
- Variable =Drukket3= har verdi 9
- Det gjelder også variabler =Drukk2a, Drukk2b= og =Drukk2c=

*** Svaret
Det er *8* for =Vil ikke svare= og *9* for =Vet ikke=
* Drukket daglig
Det er 59 svarte at de har drukket daglig siste 12 mnd =(Drukket2)=, men på spørsmål =(AL2)= antall ukedager drikker alkohol ble svarene for det 59 som følgende:

#+begin_example
> dt[Drukket2 == 1, .N, keyby = AL2]
Key: <AL2>
                AL2     N
   <haven_labelled> <int>
1:                1    34  Alle 4 ukedager
2:                2    11  3 av 4 dager
3:                3    10  2 av 4 dager
4:                4     4  1 av 4 dager
#+end_example

*** Svaret
Bruk bare variabel =(Drukket2)=
* Drikkefrekvens
For å bregne [[https://github.com/folkehelsestats/toa/blob/e101075d723efc73d317bff17d135dadffd926ec/do/toa.do#L5][alkoholdager]] bruker man variabel =Drukket2= og venner bl.a =Drukk2c=. Spørsmålet:
- Når =Drukket2= er /Sjeldnere enn månedlig/ regnes det som *7.5* dager når svaret i =Drukk2c= /Flere enn tre dager/. Se [[https://github.com/folkehelsestats/toa/blob/e101075d723efc73d317bff17d135dadffd926ec/do/toa.do#L13][koden]]
- For longitudinal data er svarene for 2012 og 2013 for variabel =drukk2c= annerledes enn de andre. Se [[https://folkehelsestats.github.io/toa/rus2012][kodebok]] dvs. /Noen få dager/ og /En dag/. Hvordan teller man alkohol dager for disse årene som i FHI [[https://www.fhi.no/le/alkohol/alkoholinorge/omsetning-og-bruk/alkoholbruk-i-den-voksne-befolkningen/#forskjeller-i-alkoholbruk-i-ulike-befolkningsgrupper][rapporten]]?

* Drikker 6+
I FHI [[https://www.fhi.no/le/alkohol/alkoholinorge/omsetning-og-bruk/alkoholbruk-i-den-voksne-befolkningen/?term=#forskjeller-i-alkoholbruk-i-ulike-befolkningsgrupper][rapporten]] står det om "Drukket 6+ siste år(%)". Er det tall som egentlig /siste fire uker/ som telles til /siste år/? Spørsmål om alkoholbruk dvs. frekvens og mengde, gjelder bare for *siste fire uker*.

*** Svaret
Bruk variable =Audit3_1= osv

* Maks verdi
Skal disse endres til missing? Foreløpig beholder disse som det er
- =flaskeroltot= og =halvlitertot= har maks verdi av 100
- =vinflaskeruke= har maks verdi av 28
- =vinflaskertot= har maks verdi av 10

*** Svaret
Vi gjør som FHI dvs. beholder alle verdiene
* Vil ikke svar og vet ikke
FHI konverterer disse til 0, men vi anser dem som missing. Disse gjelder for verdien 99998 og 99999 særlig for alkoholenhet gjennomsnitt per uke i siste 4 uker eller total ila. siste 4 uker.

*** Svaret
Det er /vil ikke svaret/ og /vet ikke/

* Ren alkohol i cl

Tall som brukes til å bregne dette. Hvilken bør vi bruke. Begreningen kan ses [[https://github.com/folkehelsestats/toa/blob/2e1ecdd268e8568d4ed9275fde50a234f5a33a36/rusund/rus-draft.R#L601][her]]

*** Svaret
Se litt mer detaljene til [[https://github.com/folkehelsestats/toa/blob/main/ref/alcohol.org][denne]] forklaringen.

* Vinglass
Et vin glass regnes som 1 alkoholenhet i spørreskjema, men Ingeborg regnet det som 1.2 alkoholenhet. Se [[https://github.com/folkehelsestats/toa/blob/33410e7ee185f240ed52124b3f35029a583f98ab/do/toa.do#L261][koden]] eller [[file:~/Git-hdir/toa/do/toa.do::gen vinenheter= (1.2*vinglassuke + 6*vinflaskeruke)*4 + 1.2*vinglasstot + 6*vinflaskertot][(do fil)]]

*** Svaret
Selv om det står at en enhet for vin er 1.5 dl, så er det 1.2 dl som er riktig siden en flasker er 0.75l og en alkoholenhet er 15ml ren alkohol

* AUDIT
- I =do= file ie. =toa.do= blir =Audit2= til =Audit8= omkodet slik:

#+begin_example
recode Audit2 (1=0)(2=1)(3=2)(4=3)(5=4)(8/9=.)
gen Audit2new=Audit2
replace Audit2new=0 if Drukket1==2
replace Audit2new=0 if Drukket1==8
#+end_example

[[https://github.com/folkehelsestats/toa/blob/33410e7ee185f240ed52124b3f35029a583f98ab/do/toa.do#L426][Se koden]]

Hvorfor skal de som ikke har drukket ie. ~Drukket1 %in% c(2,8)~ skal bli omkodet til 1 dvs. drukket 1-2. Se linje 425 i do filen.

* AUDIT 3
I =do= fil linje 432. Skal =Audit3_1= og =Audit3_2= brukes til å omkode =AUDIT3=? I =do= filen blir =Audit3_1= lik =Omtrent en dag i uken= omkodet til =månedlig=. Se [[https://github.com/folkehelsestats/toa/blob/33410e7ee185f240ed52124b3f35029a583f98ab/do/toa.do#L431][koden]]. Er det riktig? Hos [[https://www.ssb.no/helse/helseforhold-og-levevaner/statistikk/royk-alkohol-og-andre-rusmidler][SSB]] bruker det bare AUDIT3 som det er.

*** Svaret
Se den nye omkodingen for =Audit3new=
* Kontrollere nye data fra SSB for disse:
Det er noen variabler i datasettet som ikke samsvar med spørreskjema og bør sjekkes når vi får nye datasettet bl.a:
** Audit spørsmål
- For =Audit9= finnes i spørreskjema, men i datasettet finnes det bare =Audit9a= og =Audit9b= itillegg til =audit9_a=, =audit9_b= og =audit9_c= og diss finnes ikke i spørreskjema dvs. for mange variabler som i spørreskjema.

** Bruk av LSD siste 12 måneder
- Det er flere variabler i datasettet dvs. =Ans7=, =Ans7_x= og =Ans7_y=, men det er bare et spørsmål i spørreskjema.
