```{r}
#| echo: false
#| warning: false

cleanFile <- file.path("rusund", "cleaning", "history", "history-cleaning.R")
## Datasettet DD blir laget her
source(file.path(here::here(), cleanFile))

```


## Andel av alkoholbruk siste år 

```{r}
#| echo: false
#| warning: false

drkAlle <- proscat("year", "alkosistaar", d = DD, total = FALSE)
drk <- proscat("year", "alkosistaar", z = "kjonn", d = DD, total = FALSE)

## Bare de som svarte Ja
drkAlle[, kjonn := 3] #totalt
drkAlleX <- drkAlle[alkosistaar == 1]
                      
drkX <- drk[alkosistaar == 1]

drkDT <- data.table::rbindlist(list(drkAlleX, drkX), use.names = TRUE)
drkDT[, kjonn := as.integer(kjonn)]

kjonnVal <- c("Menn" = 1, "Kvinner" = 2, "Alle" = 3)
kjonnKB <- data.table(v1 = as.integer(kjonnVal),
                      v2 = names(kjonnVal))

drkDT[, kjonn := as.numeric(kjonn)]
drkDT[kjonnKB, on = c(kjonn = "v1"), kjonn2 := i.v2]
setorder(drkDT, year, kjonn)

```

::: {.panel-tabset}
## Figur
```{r}

make_hist(d = drkDT,
          x = year,
          y = percentage,
          group = kjonn2,
          n = count,
          title = "Alkoholbruk siste 12 måneder 2012-2024",
          subtitle = "Kilde: Rusundersøkelse 2012-2014 ",
          type = "line",
          dot_size = 6,
          flip = FALSE)
```

## Tabell

```{r}

drkDTT <- data.table::rbindlist(list(drkAlle, drk), use.names = TRUE)

alkoVal <- c("Drukket" = 1, "Ikke drukket" = 2)
alkoKB <- data.table(v1 = as.integer(alkoVal),
                     v2 = names(alkoVal))

drkDTT[alkoKB, on = c(alkosistaar = "v1"), alko := i.v2]
drkDTT[, kjonn := as.numeric(kjonn)]
drkDTT[kjonnKB, on = c(kjonn = "v1"), kjonn2 := i.v2]

cols <- c("alkosistaar", "sum", "kjonn")
drkDT[, (cols) := NULL]

colout <- c("alko", "year", "count", "percentage") #Column order
colns <- c(" ", "year", "Antall", "Andel") #Columns rename
setkey(drkDTT, year, alkosistaar, kjonn)
setcolorder(drkDTT, colout)
data.table::setnames(drkDTT, colout, colns)

gt::gt(drkDTT)

```
:::


<!-- Alkoholbruk siste år bland menn i ulike aldersgrupper, 2012-2024 -->

```{r}
#| echo: false
#| warning: false
#| output: false

ageBreak <- c(16, 25, 35, 45, 55, 65, Inf)
ageLab <- c("16-24", "25-34", "35-44", "45-54", "55-64", "65+")

group_age(dt = DD, var = "alder", breaks = ageBreak,
          labels = ageLab, new_var = "agecat",
          right = FALSE, missing_values = c(999, 998))


drukkMen <- proscat("year", "alkosistaar", d = DD[kjonn == 1], total = F, z = "agecat")
drukkWom <- proscat("year", "alkosistaar", d = DD[kjonn == 2], total = F, z = "agecat")

```

::: {.panel-tabset}

## Figur
```{r}
make_hist(d = drukkMen[alkosistaar == 1],
          x = year,
          y = percentage,
          group = agecat,
          n = count,
          title = "Alkoholbruk siste år bland menn i ulike aldersgrupper, 2012- 2024",
          subtitle = "Kilde: Rusundersøkelse 2012-2014 ",
          type = "line",
          dot_size = 6)

```
## Tabell

```{r}
drukkMen
```

:::

<!-- For kvinner -->

::: {.panel-tabset}

## Figur
```{r}
make_hist(d = drukkWom[alkosistaar == 1],
          x = year,
          y = percentage,
          group = agecat,
          n = count,
          title = "Alkoholbruk siste år bland kvinner i ulike aldersgrupper, 2012- 2024",
          subtitle = "Kilde: Rusundersøkelse 2012-2014 ",
          type = "line",
          dot_size = 6)

```
## Tabell

```{r}
drukkWom
```
:::


## Andel har drukket 6+ alkoholenheter ved en og samme anledning

Tallene som blir presentert her er for de som har drukket 6+ alkoholenheter
daglig eller ukentlig ved en og samme anledning i det siste året.

```{r}
## Noen koder for Audit er omvent
DD[year %in% 2012:2014,  audit3 := fcase(audit3 == 5, 1,
                                         audit3 == 4, 2,
                                         audit3 == 2, 4,
                                         audit3 == 1, 5,
                                         default = as.numeric(audit3))]

## Omkoding
DD[, drink6w := fcase(audit3 %in% 1:2, 1, #Daglig og ukenlig
                      audit3 %in% 3:4, 2, #månedlig og sjeldenere
                      audit3 == 5, 0, #aldri
                      default = NA)]

drk6 <- split_gender(d=DD, x = "year", y = "drink6w", select = 1)

```


::: {.panel-tabset}

## Figur

```{r}

make_hist(d = drk6$d2, x = year, y = percentage, n = count,  group = pop,
          title = "Drukket 6+ enheter daglig eller ukenlig ved en og samme anledning siste år",
          subtitle = "Kilde: Rusundersøkelse 2012-2014 ",
          type = "line", yint = 2)
```

## Tabell

```{r}

drk6D1 <- drk6$d1
drk6D1[, sum := NULL]

gt::gt(drk6D1)
```

:::

<!-- Drukket 6+ alder og kjønn -->

```{r}
#| echo: false
#| warning: false
#| output: false

drk6Men <- proscat("year", "drink6w", d = DD[kjonn == 1], total = F, z = "agecat")
drk6Wom <- proscat("year", "drink6w", d = DD[kjonn == 2], total = F, z = "agecat")

```

::: {.panel-tabset}

## Figur
```{r}
make_hist(d = drk6Men[drink6w == 1],
          x = year,
          y = percentage,
          group = agecat,
          n = count,
          title = "Drukket 6+ enheter daglig eller ukenlig ved en og samme anledning siste år",
          subtitle = "Menn, 2012-2024",
          type = "line")

```
## Tabell

```{r}
drk6Men
```

:::

<!-- For kvinner -->

::: {.panel-tabset}

## Figur
```{r}
make_hist(d = drk6Wom[drink6w == 1],
          x = year,
          y = percentage,
          group = agecat,
          n = count,
          title = "Drukket 6+ enheter daglig eller ukenlig ved en og samme anledning siste år",
          subtitle = "Kvinner, 2012-2024",
          type = "line")

```
## Tabell

```{r}
drk6Wom
```
:::

