```{r setup-2024}
#| echo: false
#| warning: false

cleanFile <- file.path("rusund", "cleaning", "rus2024", "rus-draft.R")
## Datasettet DD blir laget her
source(file.path(here::here(), cleanFile))
```

## Andel som har drukket siste år i 2024

```{r cal2-druk}
#| echo: false
#| warning: false

dt[, Drukket1 := as.integer(Drukket1)]
dt[, alkosistaar := fifelse(Drukket1 == 8, NA, Drukket1)]

codebook::var_label(dt$alkosistaar) <- "Alkohol siste 12 måneder"
alksistaar_values <- c(
  "drukket alkohol siste 12 mnd" = 1,
  "ikke drukket alkohol siste 12 mnd" = 2
)

dt[, kj := as.numeric(Kjonn)]
alko <- proscat("kj", "alkosistaar")

kjonnkb <- data.table(v1 = unique(alko$kj), v2 = c("Menn", "Kvinner", "Totalt"))
alkkb <- data.table(v1 = as.integer(alksistaar_values),
                    v2 = names(alksistaar_values))

alko[kjonnkb, on = c(kj = "v1"), gender := i.v2]
alko[alkkb, on = c(alkosistaar ="v1"), alkoyr := i.v2]

```

::: {.panel-tabset}

## Figur

```{r}
make_hist(d = alko,
          x = gender,
          y = percentage,
          group = alkoyr,
          n = count,
          title = "Alkohol siste 12 måneder")
```

## Tabell

```{r}
cols <- c("kj", "alkosistaar", "sum")
alko[, (cols) := NULL]

colout <- c("alkoyr", "gender", "count", "percentage")
colns <- c(" ", "Kjønn", "Antall", "Andel")
setcolorder(alko, colout)
data.table::setnames(alko, colout, colns)

gt::gt(alko)

```
:::



## Drikkefrekvens siste år

```{r}

alkofrekvens_values <- c(
    "aldri drukket" = 0,
    "ikke drukket siste år" = 1,
    "drukket sjeldnere enn månedlig siste 12 mnd" = 2,
    "drukket månedlig siste 12 mnd" = 3,
    "drukket ukentlig siste 12 mnd" = 4,
    "drukket daglig siste 12 mnd" = 5
)

dt[, kj := as.numeric(Kjonn)]
alkofreq <- proscat("kj", "alkofrekvens")

afKB <- data.table(v1 = as.integer(alkofrekvens_values),
                   v2 = names(alkofrekvens_values))

alkofreq[kjonnkb, on = c(kj = "v1"), gender := i.v2]
alkofreq[afKB, on = c(alkofrekvens = "v1"), alkof := i.v2]
```

::: {.panel-tabset}
## Figur

```{r}
alkofreq[, alkofrekvens := as.numeric(alkofrekvens)]

make_hist(d = alkofreq,
          x = gender,
          y = percentage,
          group = alkof,
          n = count,
          title = "Drikkerfrekvens siste 12 måneder")

```

## Tabell

```{r}
cols <- c("kj", "alkofrekvens", "sum")
alkofreq[, (cols) := NULL]

colout <- c("alkof", "gender", "count", "percentage")
colns <- c(" ", "Kjønn", "Antall", "Andel")
setcolorder(alkofreq, colout)
data.table::setnames(alkofreq, colout, colns)

gt::gt(alkofreq)

```

:::


## Andel som har drukket 6+ enheter siste 4 uker 
- En alkoholenhet tilsvarer 0,33 l øl, 1,5 dl vin eller en 4 cl brennevin.
- Andel som har drukket 6+ enheter ved samme anledning minst en gang 4 ukene 


```{r}
## Nevner inkluderer de som ikke har drukket siste år også dvs. drukket1=2(Nei)
dt[, drink6 := fcase(Audit3 %in% 1:4, 1, #Daglig, ukenlig, månedlig og sjeldenere
                     Audit3 == 5, 0, #aldri
                     Drukket1 == 2, 0,
                     default = NA)]

drk6_24 <- proscat(x = "kj", y = "drink6", d = dt, total = TRUE)
kjonnkb <- data.table(v1 = 0:2, v2 = c("Menn", "Kvinner", "Totalt"))
alkokb <- data.table(v1 = 0:1, v2 = c("Aldri", "Drukket 6+"))
drk6_24[kjonnkb, on = c(kj = "v1"), gender := i.v2]
drk6_24[alkokb, on = c(drink6 = "v1"), alko := i.v2]

```

::: {.panel-tabset}

## Figur
```{r}
make_hist(d = drk6_24,
          x = gender,
          y = percentage,
          group = alko,
          n = count,
          title = "Andel drukket 6+ enheter siste 4 uker")
```

## Tabell
```{r}
cols <- c("kj", "drink6", "sum")
drk6_24[, (cols) := NULL]

colout <- c("alko", "gender", "count", "percentage")
colns <- c(" ", "Kjønn", "Antall", "Andel")
setcolorder(drk6_24, colout)
data.table::setnames(drk6_24, colout, colns)

gt::gt(drk6_24)

```
:::

